SCSTLogicalUnit: re-introduce STANDBY variable, to use "standby" mode for qla2x00t

diff --git a/heartbeat/SCSTLogicalUnit b/heartbeat/SCSTLogicalUnit
--- a/heartbeat/SCSTLogicalUnit
+++ b/heartbeat/SCSTLogicalUnit
@@ -90,6 +90,15 @@ CIB_XPATH_CONNECTIVITY="${HA_SBIN_DIR}/cibadmin --query --local --xpath \
     //node_state[@uname=\"${HOSTNAME}\"]/transient_attributes//nvpair[starts-with(@name,\"#SCST${OCF_RESKEY_fabric}\")]"
 STORCLI="${OCF_RESKEY_storcli_binary_path}"
 
+# Forwarding targets are currently only supported
+# by iscsi fabrics
+if [ "${OCF_RESKEY_fabric}" == "qla2x00t" ]; then
+    STANDBY="standby"
+else
+    STANDBY="nonoptimized"
+fi
+
+
 # Lockfile, for LUs starting in parallel
 LOCKFILE=${HA_RSCTMP}/SCSTLogicalUnit.lock
 #######################################################################
@@ -786,10 +795,10 @@ SCSTLogicalUnit_start() {
                 scst_sysfs_write "0" ${dev_group}/target_groups/${tpg}/preferred || {
                     ocf_log err "Unable to set \"preferred\" to 0 - TPG ${tpg}, device_group ${OCF_RESOURCE_INSTANCE}.";
                 }
-                scst_sysfs_write "nonoptimized" ${dev_group}/target_groups/${tpg}/state || {
-                    ocf_log err "Unable to set state to \"nonoptimized\" - TPG ${tpg}, device_group ${OCF_RESOURCE_INSTANCE}.";
+                scst_sysfs_write "${STANDBY}" ${dev_group}/target_groups/${tpg}/state || {
+                    ocf_log err "Unable to set state to \"${STANDBY}\" - TPG ${tpg}, device_group ${OCF_RESOURCE_INSTANCE}.";
                 }
-                ocf_log debug "${OCF_RESOURCE_INSTANCE}: TPG ${tpg} for device_group ${OCF_RESOURCE_INSTANCE} is nonoptimized."
+                ocf_log debug "${OCF_RESOURCE_INSTANCE}: TPG ${tpg} for device_group ${OCF_RESOURCE_INSTANCE} is ${STANDBY}."
 
                 # Sort the targets in local_targets (like the TPGs) so we can
                 # apply "rel_tgt_id"s in a consistent way.
@@ -891,7 +900,7 @@ SCSTLogicalUnit_monitor() {
 
     handler_path="${SCST_BASE}/handlers/${OCF_RESKEY_device_handler}"
     dev_path="${handler_path}/${OCF_RESOURCE_INSTANCE}"
-    alua_state="nonoptimized"
+    alua_state="${STANDBY}"
     index=${#ids[@]}
 
     # If our backing device (or file) doesn't even exist, we're not running
@@ -975,7 +984,7 @@ SCSTLogicalUnit_promote() {
 
     case $rc in
         $OCF_SUCCESS)
-            ocf_log debug "${OCF_RESOURCE_INSTANCE}: ALUA - currently in Slave state, TPG $HOSTNAME is nonoptimized/not-preferred"
+            ocf_log debug "${OCF_RESOURCE_INSTANCE}: ALUA - currently in Slave state, TPG $HOSTNAME is ${STANDBY}/not-preferred"
             ;;
         $OCF_NOT_RUNNING)
             ocf_log info "ALUA: Trying to promote resource ${OCF_RESOURCE_INSTANCE} that is not running, start it ..."
@@ -1016,7 +1025,7 @@ SCSTLogicalUnit_demote() {
             exit $OCF_ERR_GENERIC
             ;;
         $OCF_SUCCESS)
-            ocf_log debug "${OCF_RESOURCE_INSTANCE}: ALUA - already in Slave state, TPG $HOSTNAME is in nonoptimized mode"
+            ocf_log debug "${OCF_RESOURCE_INSTANCE}: ALUA - already in Slave state, TPG $HOSTNAME is in ${STANDBY} mode"
             return $OCF_SUCCESS
             ;;
         *)
@@ -1025,11 +1034,11 @@ SCSTLogicalUnit_demote() {
     esac
 
     # Now do the demotion
-    update_alua_access_state $HOSTNAME nonoptimized || {
-        ocf_log error "Unable to set ALUA access state for lun_${OCF_RESKEY_lun}/${OCF_RESOURCE_INSTANCE} to nonoptimized!";
+    update_alua_access_state $HOSTNAME ${STANDBY} || {
+        ocf_log error "Unable to set ALUA access state for lun_${OCF_RESKEY_lun}/${OCF_RESOURCE_INSTANCE} to ${STANDBY}!";
         exit $OCF_ERR_GENERIC
     }
-    ocf_log debug "${OCF_RESOURCE_INSTANCE}: ALUA - demote was successfull, TPG $HOSTNAME is now nonoptimized"
+    ocf_log debug "${OCF_RESOURCE_INSTANCE}: ALUA - demote was successfull, TPG $HOSTNAME is now ${STANDBY}"
 
     # In case of a block device, flush any outstanding I/O to the device
     flushbufs
@@ -1063,7 +1072,7 @@ SCSTLogicalUnit_notify() {
                     done
                 else
                     # Be sure to set correct slave mode
-                    update_alua_access_state $node nonoptimized
+                    update_alua_access_state $node ${STANDBY}
                 fi
             done
             ;;
@@ -1076,7 +1085,7 @@ SCSTLogicalUnit_notify() {
         post/demote)
             for node in $demoteit; do
                 # Switch all new slave instances TPG to standby
-                update_alua_access_state $node nonoptimized
+                update_alua_access_state $node ${STANDBY}
             done
             ;;
         post/stop)
