SCSTLogicalUnit: block_dev() and unblock_dev() now also works with multiple existing blocks

diff --git a/heartbeat/SCSTLogicalUnit b/heartbeat/SCSTLogicalUnit
--- a/heartbeat/SCSTLogicalUnit
+++ b/heartbeat/SCSTLogicalUnit
@@ -362,9 +362,8 @@ block_dev() {
     if [ -e "${block}" ]; then
         ocf_log info "${OCF_RESOURCE_INSTANCE}: Waiting for device ${OCF_RESOURCE_INSTANCE} being blocked..."
         # Check if device is already blocked
-        if [ "$(scst_sysfs_read ${block})" != "1 0" -a  "$(scst_sysfs_read ${block})" != "1 1" ]; then
-            # This is synchronous and waits for all running commands
-            # being drained.
+        if scst_sysfs_read ${block} | egrep -qv '[1-9][0-9]* [01]'; then
+            # Do an synchronous block
             scst_sysfs_write "1" ${block} || {
                 ocf_log err "Unable to block device ${OCF_RESOURCE_INSTANCE}.";
                 exit $OCF_ERR_GENERIC
@@ -380,11 +379,16 @@ unblock_dev() {
     # Unblock the previously blocked device.
     if [ -e "${block}" ]; then
         # Check if device is already unblocked
-        if [ "$(scst_sysfs_read ${block})" != "0 0" -a  "$(scst_sysfs_read ${block})" != "0 1" ]; then
-            scst_sysfs_write "0" ${block} || {
-                ocf_log err "Unable to unblock device ${OCF_RESOURCE_INSTANCE}.";
-                exit $OCF_ERR_GENERIC
-            }
+        if scst_sysfs_read ${block} | egrep -qv '0 [01]'; then
+            # Wait until unblock is finished, there
+            # could be more than one "block"
+            until scst_sysfs_read ${block} | egrep -q '0 [01]'; do
+                scst_sysfs_write "0" ${block} || {
+                    ocf_log err "Unable to unblock device ${OCF_RESOURCE_INSTANCE}.";
+                    exit $OCF_ERR_GENERIC
+                }
+                sleep 0.$(ocf_maybe_random)
+            done
         fi
         ocf_log info "${OCF_RESOURCE_INSTANCE}: Successfully unblocked device ${OCF_RESOURCE_INSTANCE}."
     fi
